### ISSUE TITLE
Add region/partition information as a prefix to log statements

### ISSUE THREAD

**Issue by johannkm** [ctring/SLOG#9]
Adding region and partition ids as a prefix to log statements would help readability. Unfortunately it looks like GLOG does not support custom prefixes: https://github.com/google/glog/issues/229#issuecomment-322453611. We could write a wrapper for the log macro? Might be more work than it's worth?

@ctring

**Comment by ctring** [comment]
I thought about this before but we only need this in unit tests because the logs are interleaved in one terminal. Later on when things are more stable, we'll most often run different processes with logging on different terminals; or run with Docker, and log of a particular process can be watched with `docker container logs`
